{% set version = "1.1.1" %}
{% set sha256 = "af36441272289b54f2eeb9b880043c64d290d35b5b62ffbf72748f2ef7232d27" %}
{% set libgd_version = "2.3.0" %}

package:
  name: py_gd
  version: {{ version }}

source:
  fn: py_gd-{{ version }}.tar.gz
  url: https://github.com/NOAA-ORR-ERD/py_gd/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - libgd {{ libgd_version }}
    - cython
    - numpy

  run:
    - python
    - libgd {{ libgd_version }}
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pytest
  imports:
    - py_gd
  commands:
    - py.test --pyargs py_gd

about:
  home: https://github.com/NOAA-ORR-ERD/py_gd
  license: CC0-1.0
  summary: Pythonic wrappers for the libgd graphics rendering library

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - jay-hennen
    - JamesMakela-NOAA
