{% set version = "2.2.1" %}
{% set sha256 = "c21d0c7eaaeaafca02aec72d5cda5324ba397a2eaf609ec7613a9f9e7145a5e8" %}
{% set libgd_version = "2.3.*" %}

package:
  name: py_gd
  version: {{ version }}

source:
  fn: py_gd-{{ version }}.tar.gz
  url: https://github.com/NOAA-ORR-ERD/py_gd/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<38 or python_impl == 'pypy']

requirements:
  build:
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - libgd {{ libgd_version }}              # [build_platform != target_platform]
    - cython ==0.29.*                        # [build_platform != target_platform]
  host:
    - python
    - pip
    - libgd {{ libgd_version }}
    - cython ==0.29.*
    - numpy

  run:
    - python
    - {{ pin_compatible('libgd') }}
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pytest
  imports:
    - py_gd
  commands:
    - py.test --pyargs py_gd

about:
  home: https://github.com/NOAA-ORR-ERD/py_gd
  license: CC0-1.0
  summary: Pythonic wrappers for the libgd graphics rendering library

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - jay-hennen
    - JamesMakela-NOAA
