{% set version = "2.0.0" %}
{% set sha256 = "499fd6366c677eccc09e9db702ce4340a0cee852511af33d50e4ea62faaaec5d" %}
{% set libgd_version = "2.3.0" %}

package:
  name: py_gd
  version: {{ version }}

source:
  fn: py_gd-{{ version }}.tar.gz
  url: https://github.com/NOAA-ORR-ERD/py_gd/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python>=3.8
    - pip
    - libgd {{ libgd_version }}
    - cython
    - numpy

  run:
    - python>=3.8
    - libgd {{ libgd_version }}
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pytest
  imports:
    - py_gd
  commands:
    - py.test --pyargs py_gd

about:
  home: https://github.com/NOAA-ORR-ERD/py_gd
  license: CC0-1.0
  summary: Pythonic wrappers for the libgd graphics rendering library

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - jay-hennen
    - JamesMakela-NOAA
