{% set version = "2.3.0" %}
{% set sha256 = "fe25ed8f6a83d5249d000a5c6ec5dc5a835e53a88f471d52a76b6b70caa908d6" %}
{% set libgd_version = "2.3.*" %}

package:
  name: py_gd
  version: {{ version }}

source:
  fn: py_gd-{{ version }}.tar.gz
  url: https://github.com/NOAA-ORR-ERD/py_gd/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<39]
  skip: true  # [python_impl == 'pypy']

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - libgd {{ libgd_version }}              # [build_platform != target_platform]
    - cython >=3                                # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - libgd {{ libgd_version }}
    - cython >=3
    - numpy

  run:
    - python
    - {{ pin_compatible('libgd') }}

test:
  requires:
    - pytest
  imports:
    - py_gd
  commands:
    - py.test --pyargs py_gd

about:
  home: https://github.com/NOAA-ORR-ERD/py_gd
  license: CC0-1.0
  summary: Pythonic wrappers for the libgd graphics rendering library

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - jay-hennen
    - JamesMakela-NOAA
