{% set version = "2.2.0" %}
{% set sha256 = "7dbf523f475fb90dd2acf47d9edbd7f215e90f0a8d59047bae54e6d302a65caf" %}
{% set libgd_version = "2.3.*" %}

package:
  name: py_gd
  version: {{ version }}

source:
  fn: py_gd-{{ version }}.tar.gz
  url: https://github.com/NOAA-ORR-ERD/py_gd/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<38 or python_impl == 'pypy']

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - libgd {{ libgd_version }}
    - cython ==0.29.*
    - numpy >=1.19

  run:
    - python
    - {{ pin_compatible('libgd') }}
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pytest
  imports:
    - py_gd
  commands:
    - py.test --pyargs py_gd

about:
  home: https://github.com/NOAA-ORR-ERD/py_gd
  license: CC0-1.0
  summary: Pythonic wrappers for the libgd graphics rendering library

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - jay-hennen
    - JamesMakela-NOAA
